{% set name = "rascil" %}
#{% set version = "0.7.dev0" %}

#source:
#  git_url: https://gitlab.com/ska-telescope/external/rascil
#  git_rev: {{ version }}

build:
  noarch: python
  number: 0
  script_env:
    - PKG_VERSION

package:
  name: {{ name|lower }}
  version: {{ PKG_VERSION }}

requirements:
  build:
    - python
    - pip
    - git-lfs
    - git
  host:
    - python
    - pip
    - curl
  run:
   - python
   - aotools
   - astropy
   - astroplan
   - bdsf >=1.10
   - bokeh
   - configparser
   - dask
   - dask-memusage
   - distributed
   - ducc0
   - gitpython
   - python-graphviz
   - h5py ==3.6
   - matplotlib
   - numpy
   - pandas
   - paramiko
   - photutils
   - python-casacore
   - python-gitlab
   - reproject
   - scipy
   - tabulate
   - xarray ==2022.3.0
   - zarr

test:
  imports:
    - rascil

about:
  home: https://gitlab.com/ska-telescope/external/rascil.git
  license: APACHE
  license_family: APACHE
  license_file: LICENSE
  summary: 'Radio Astronomy Simulation, Calibration and Imaging Library'
  description: |
   The Radio Astronomy Simulation, Calibration and Imaging Library expresses radio interferometry calibration and imaging algorithms in python and numpy. The interfaces all operate with familiar data structures such as image, visibility table, gain table, etc. The python source code is directly accessible from these documentation pages: see the source link in the top right corner.
  doc_url: https://ska-telescope.gitlab.io/external/rascil/index.html
  dev_url: https://gitlab.com/ska-telescope/external/rascil.git

extra:
  recipe-maintainers:
    - Lukas Gehrig
