name: Package Rascil

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install Rascil
        run: |
          chmod +x build.sh
          ./build.sh
