name: Build Conda Package Rascil

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/mambabuild-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Conda
        shell: bash -l {0}
        run: |
          cd conda
          conda mambabuild -c i4ds -c conda-forge .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/noarch/rascil-*.tar.bz2 --force



  install_and_test:
    needs: build
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/mambabuild-docker:latest
    steps:
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda config --append channels conda-forge
          
          conda create -n testpy37 python=3.7
          conda activate testpy37
          mamba install -c i4ds -c conda-forge rascil
          python -c "import rascil" 
          
          conda create -n testpy38 python=3.8
          conda activate testpy38
          mamba install -c i4ds -c conda-forge rascil
          python -c "import rascil"
          
          conda create -n testpy39 python=3.9
          conda activate testpy39
          mamba install -c i4ds -c conda-forge rascil
          python -c "import rascil"
