name: Package Rascil

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: Install Rascil
        uses: actions/checkout@v2
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload PyBDSF Wheel
        uses: actions/upload-artifact@v2
        with:
          name: PyBDSF Wheel ${{ runner.os }}
          path: |
            dist/*.whl