name: Build Conda Package Rascil

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install conda build
        shell: bash -l {0}
        run: |
          conda create -n build_env 
          conda activate build_env
          conda install -c conda-forge anaconda boa
          conda config --append channels conda-forge
          conda config --append channels i4ds
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Conda
        shell: bash -l {0}
        run: |
          conda activate build_env
          cd conda
          conda mambabuild .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate build_env
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/rascil-*.tar.bz2 --force
