name: Package Rascil

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Rascil
        run: |
          chmod +x build.sh
          ./build.sh
      - name: Upload PyBDSF Wheel
        uses: actions/upload-artifact@v2
        with:
          name: PyBDSF_Wheel_${{ runner.os }}
          path: |
            ${{ github.workspace }}/bdsf/dist/*.whl
  install_and_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download wheel
        uses: actions/download-artifact@v2
      - name:
        run: |
          pip3 install PyBDSF_Wheel_Linux/*.whl
          pip3 install matplotlib
          pip3 list
          python3 test.py
